apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: team_name
spec:
  groups:
    - system:authenticated
  request: request
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
